#!/bin/sh

PROFILE=$1
OSCODE=$2

if [ "x${PROFILE}" = "x" ]; then
    echo "Usage: $0 PROFILE [oscode]" 1>&2;
    exit 1
fi

if [ ! -e "profiles/${PROFILE}.conf" ]; then
    echo "Unknown profile: ${PROFILE}" 1>&2;
    exit 1
fi

if [ "x${OSCODE}" = "x" ]; then
    OSCODE="$(lsb_release -c | awk '{print $2}')"
  echo "Defaulted OSCODE to ${OSCODE}"
fi


if [ "$(id -u)" -eq 0 ]; then
    ROOT_CMDOPTS='--force-root'
else
    ROOT_CMDOPTS=''
fi

if [ -e profiles/default.preseed ]; then
    rm -f profiles/default.preseed
fi

if [ -e "profiles/${PROFILE}.prerun" ]; then
   PRERUN="profiles/${PROFILE}.prerun"
   if $PRERUN; then
       echo "profiles/${PROFILE}.prerun returned error. Aborting" 1>&2
       exit 1
   fi
fi

REMOVE_KEYBOARD_PROMPTS="--keyboard us --locale en_US.UTF-8"
build-simple-cdd --conf "profiles/${PROFILE}.conf" \
    --dist "${OSCODE}" "${ROOT_CMDOPTS}" "${REMOVE_KEYBOARD_PROMPTS}"
